server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    hosts:
      - argo.k8s.twy.gmbh
    tls:
      - secretName: argo-k8s-twy-gmbh
        hosts:
          - argo.k8s.twy.gmbh
