apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-nfs-pv
  labels:
    type: vaultwarden-nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.1.111
    path: "/volume1/k8s/vaultwarden"
---
# Source: vaultwarden/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: vaultwarden
  annotations:
    meta.helm.sh/release-name: vaultwarden-release
    meta.helm.sh/release-namespace: vaultwarden
  labels:
    app.kubernetes.io/instance: vaultwarden-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/version: 1.30.1
    helm.sh/chart: vaultwarden-0.19.0
  name: vaultwarden-data-vaultwarden-release-0
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: vaultwarden-nfs
  volumeName: vaultwarden-nfs-pv
