# Source: vaultwarden/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-release
  namespace: vaultwarden
  labels:
    app.kubernetes.io/component: vaultwarden
    helm.sh/chart: vaultwarden-0.19.0
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/instance: vaultwarden-release
    app.kubernetes.io/version: "1.30.1"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  SMTP_PASSWORD: ""
  SMTP_USERNAME: ""
  ADMIN_TOKEN: "JGFyZ29uMmlkJHY9MTkkbT0xOTQ1Nix0PTIscD0xJFZreDFWa0U0Um1oRE1VaHdObTlZVmxoUFFrVk9aazFZYzFkdVNEZEdSVll6ZDBZNVprZ3dhVmcwWXowJFBLK2gxQU5DYnp6bUVLYWlRZkNqV3craFdGYU1LdkxoRzJQalJhbkg1S2s="
---
kubectl -n vaultwarden create secret generic secret-vaultwarden \
--from-literal=SMTP_PASSWORD= \
--from-literal=SMTP_USERNAME= \
--from-literal=ADMIN_TOKEN=$argon2i$v=19$m=16,t=2,p=1$c1VRVDRVTzhnYzRQUHdWNA$BdcujHHLzzhGKNJvSEWSww \
--dry-run=client \
-o yaml > sealed-secret-vaultwarden.yaml