# Source: csi-driver-nfs/templates/rbac-csi-nfs.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-nfs-node-sa
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: "csi-driver-nfs"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/name: "csi-driver-nfs"
    app.kubernetes.io/version: "v4.5.0"
    helm.sh/chart: "csi-driver-nfs-v4.5.0"
