apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cv-ui-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - reto.k8s.twy.gmbh
      secretName: reto-k8s-twy-gmbh
  rules:
    - host: reto.k8s.twy.gmbh
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: cv-ui
                port:
                  number: 80
