apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cv-ui-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cv-ui
                port:
                  number: 80
  tls:
    - hosts:
        - cv.k8s.twy.gmbh
