apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cv-ui-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - cv.k8s.twy.gmbh
      secretName: cv-tls
  rules:
    - host: cv.k8s.twy.gmbh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cv-ui
                port:
                  number: 80
