apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: mypostgres
  namespace: default

spec:
  replicas: 1
  image: postgres:16.1

  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000

  database:
    size: 2Gi
    storageClassName: nfs-csi-retain

  env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mypostgres-secret
          key: superUserPassword

    - name: POSTGRES_REPLICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mypostgres-secret
          key: replicationUserPassword
