# Source: argo-cd/templates/argocd-repo-server/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: argo-release-argocd-repo-server
  namespace: "argo"
  labels:
    helm.sh/chart: argo-cd-5.52.1
    app.kubernetes.io/name: argocd-repo-server
    app.kubernetes.io/instance: argo-release
    app.kubernetes.io/component: repo-server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: "v2.9.3"
