# Source: argo-cd/templates/argocd-applicationset/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: argo-release-argocd-applicationset-controller
  namespace: "argo"
  labels:
    helm.sh/chart: argo-cd-5.52.1
    app.kubernetes.io/name: argocd-applicationset-controller
    app.kubernetes.io/instance: argo-release
    app.kubernetes.io/component: applicationset-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: "v2.9.3"
spec:
  type: ClusterIP
  ports:
  - name: webhook
    port: 7000
    targetPort: webhook
  selector:
    app.kubernetes.io/name: argocd-applicationset-controller
    app.kubernetes.io/instance: argo-release
